app:
  name: kc-client-operator
  image:
    repository: "onecx/onecx-iam-kc-client-operator"
  envCustom:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
  serviceAccount:
    enabled: true
  operator:
    microservice:
      spec:
        description: OneCX IAM Keycloak Client Operator
        name: OneCX IAM KC Client Operator
